project:
  type: website

website:
  title: "Conceptual Obstacles in Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - treatment.qmd
      - communication.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

